version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "${MY_WEBSERVER_PORT}:80"
    volumes:
      - ./podcasts:/usr/share/nginx/html
  yt-podcast:
    #image: ghcr.io/rubenmartinm/yt-podcast:latest
    image: rmmonteagudo/yt-podcast:latest
    container_name: yt-podcast
    user: "${UID}:${GID}"
    restart: no
    environment:
      MY_WEBSERVER_IP: ${MY_WEBSERVER_IP}
      MY_WEBSERVER_PORT: ${MY_WEBSERVER_PORT}
    volumes:
      - ./config:/config
      - ./podcasts:/podcasts
